name: Run Azure Login with OpenID Connect and PowerShell
on: [push]

permissions:
      id-token: write
      contents: read
      
jobs: 
  Windows-latest:
      runs-on: windows-latest
      environment: 'PreProd'
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Log in to Azure
      - name: Azure Login
        uses: azure/actions/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}      